name             'go'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures go'
long_description 'Installs/Configures go'
version          '0.1.0'
